---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semaphore
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      containers:
      - name: semaphore
        image: semaphoreui/semaphore:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: semaphore-config
        env:
        - name: SEMAPHORE_DB_HOST
          value: postgres
        - name: SEMAPHORE_DB_PORT
          value: "5432"
        - name: SEMAPHORE_DB_DIALECT
          value: postgres
        - name: SEMAPHORE_DB
          value: semaphore
        dependsOn:
        - name: postgres
